"""empty message

Revision ID: 537382aeaf57
Revises: 
Create Date: 2021-09-05 13:50:43.242942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537382aeaf57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('short_url', sa.String(length=6), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('short_url'),
    sa.UniqueConstraint('original_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
